name: rutafit
description: "Prueba Técnica RutaFit – app fitness Flutter"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  http: ^1.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shimmer: ^2.0.0
  flutter_staggered_animations: ^1.0.0
  url_launcher: ^6.2.6
  flutter_reactive_ble: ^5.0.3
  permission_handler: ^11.3.0
  salomon_bottom_bar: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
